Add PHPUnit
Dylan-DPC/guzzle-client pull request #19
Opened 2017-10-04 01:29 UTC by mustorze

Hi!

I've added Phpunit and Orchestra to helps with tests.

hope your enjoy.

have nice tests xD

2017-10-04 12:40 UTC, Dylan-DPC-zz requested changes

2017-10-04 12:40 UTC, Dylan-DPC commented on tests/Functional/initializeTest.php
> +	function guzzle_initialize()
I don't need this test

2017-10-04 12:52 UTC, Dylan-DPC commented
references #16

2017-10-04 22:27 UTC, mustorze commented
Okay, test deleted.

If your have some function do you like to test, i can do it. I really don't know anything about your package, then i no have idea to do the tests

2017-10-04 22:27 UTC, Dylan-DPC-zz requested changes

2017-10-04 22:27 UTC, Dylan-DPC commented on composer.json
> +        "orchestra/database": "^3.5",
do i really need database? cause the package isn't interacting with DB at all.

2017-10-04 22:28 UTC, Dylan-DPC commented
Yes. Somebody else is already attempting the tests.

2017-10-04 22:58 UTC, mustorze commented
yea, don't needed. 

i put by habit haha.

--

Ok, if in the future had some tests to do, i will be happy helping the package. =)

2017-10-05 07:15 UTC, merged

2017-10-08 15:50 UTC, Dylan-DPC commented
If you want you can write tests for the function. Haven't heard from the other guy as yet